apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pimcore.fullname" . }}-init-app-scripts
  labels:
    {{- include "pimcore.labels" . | nindent 4 }}
data:
  pre-init-app.sh: |
    #!/bin/sh
    set -e

    echo "Waiting for database at {{ printf "%s-mariadb" .Release.Name }}:3306 ..."
    until mariadb-admin ping -h"{{ printf "%s-mariadb" .Release.Name }}" -u"${PIMCORE_INSTALL_MYSQL_USERNAME}" -p"${PIMCORE_INSTALL_MYSQL_PASSWORD}" --silent; do
      echo "... not yet"
      sleep 5
    done
    echo "Database is available."
    echo "copy configs"
    mkdir -p /var/www/html/config/packages
    cp /data/config/packages/* /var/www/html/config/packages/
    echo "Setting ownership for /var/www/html ..."
    chown -R 33:33 /var/www/html || true

  init-app.sh: |
    #!/bin/sh
    set -e

    if [ -f /var/www/html/composer.json ]; then
      echo ""
      echo "Pimcore seems to be already installed"
      echo ""

    else
      echo ""
      echo "Pimcore is not installed yet"
      echo "Create Pimcore project"
      echo ""
      composer config --global allow-plugins.php-http/discovery true
      composer create-project {{ .Values.pimcorePackage }} new-project

      echo ""
      echo "Copy new project to /var/www/html"
      echo ""
      rm -f ./new-project/config/bundles.php || true
      cp -a new-project/. ./
      rm -rf new-project

      echo ""
      echo "Install Pimcore"
      echo ""
      php vendor/bin/pimcore-install --no-interaction
    fi

    {{- if .Values.php.removeBundles }}
    # Uninstall bundles
    {{- range $bundle := .Values.php.removeBundles }}
    BUNDLE_SHORT="{{ $bundle }}"
    BUNDLE_SHORT="${BUNDLE_SHORT##*\\}"
    echo "Uninstalling bundle: $BUNDLE_SHORT"
    bin/console pimcore:bundle:uninstall $BUNDLE_SHORT || true
    {{- end }}
    {{- end }}

    {{- if .Values.php.removePackages }}
    # Remove packages
    echo "Removing packages:{{- range $e := .Values.php.removePackages }} {{ $e }}{{ end }}"
    composer remove{{- range $e := .Values.php.removePackages }} {{ $e }}{{- end }}
    {{- end }}

    {{- if .Values.php.packages }}
    # Install packages
    echo "Installing packages:{{- range $e := .Values.php.packages }} {{ $e }}{{ end }}"
    composer require{{- range $e := .Values.php.packages }} {{ $e }}{{- end }}
    {{- end }}

    {{- if .Values.php.bundles }}
    # install bundles
    {{- range $bundle := .Values.php.bundles }}
    BUNDLE_SHORT="{{ $bundle }}"
    BUNDLE_SHORT="${BUNDLE_SHORT##*\\}"
    echo "Installing bundle: $BUNDLE_SHORT"
    bin/console pimcore:bundle:install $BUNDLE_SHORT
    {{- end }}
    {{- end }}


  bundles.php: |
    <?php
    return [
        //Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    {{- range $bundle := .Values.php.bundles }}
        {{ $bundle }}::class => ['all' => true],
    {{- end }}
    {{- range $bundle := .Values.php.removeBundles }}
        {{ $bundle }}::class => ['all' => true],
    {{- end }}
    ];

