apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pimcore.fullname" . }}-php-env
  labels:
    {{- include "pimcore.labels" . | nindent 4 }}
data:
  COMPOSER_HOME: "/var/www/html"
  PHP_IDE_CONFIG: "serverName=localhost"
  PIMCORE_INSTALL_MYSQL_USERNAME: {{ .Values.mariadb.auth.username | quote }}
  PIMCORE_INSTALL_MYSQL_PORT: "3306"
  PIMCORE_INSTALL_MYSQL_HOST_SOCKET: {{ printf "%s-mariadb" .Release.Name | quote }}
  PIMCORE_INSTALL_MYSQL_DATABASE: {{ .Values.mariadb.auth.database | quote }}
{{- range $key, $value := .Values.php.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}