apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pimcore.fullname" . }}-php-env
  labels:
    {{- include "pimcore.labels" . | nindent 4 }}
type: Opaque
data:
  MESSENGER_TRANSPORT_DSN: {{ (printf "amqp://%s:%s@%s-rabbitmq:5672" .Values.rabbitmqUser .Values.rabbitmqPassword .Release.Name) | b64enc | quote }}
{{- range $key, $value := .Values.php.secretEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}